name: sharptrack
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  telephony: ^0.2.0
  audioplayers: ^1.1.1
  volume_control: ^0.1.5
  provider: ^6.0.5
  sound_mode: ^2.0.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_background: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/